name: CI
on: [push, pull_request]
jobs:
  test:
    name: Unittests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        dc: [dmd-latest] # temporary disable ldc-latest since there' no std.checkedint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install D Compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - uses: actions/cache@v2
        with:
          path: ~/.dub
          key: ${{ matrix.dc }}-${{ matrix.os }}-dub-${{ hashFiles('**/dub.selections.json') }}
          restore-keys: |
            ${{ matrix.dc }}-${{ matrix.os }}-dub-
      - name: Run tests
        run: dub test
